### PR TITLE
refactor /wallet/transactions response

### PR DESCRIPTION
**Pull request by therealssj**
skycoin/skycoin/issues/1080

### CODE REVIEW

**Comment by therealssj** [comment]
oh okay

**Comment by gz-c** [comment]
Can you show me what the API response is like now, so I can compare the change?

**Comment by therealssj** [comment]
screen shot 2018-03-16 at 6 04 14 pm
@gz-c here is a screenshot of how it looks now

**Comment by gz-c** [comment]
The gui.Client doesn't need any change?

**Comment by therealssj** [comment]
@gz-c done

**Comment by iketheadore** [comment]
The `/wallet/transactions` is not being used, maybe we can deprecate it.

**Pull request merged**
