### PR TITLE
Resolved formatting and other issues in source code.

### PR DESCRIPTION
**Pull request by Ch3ck**
*Resolved conflicts  from merge with master

### CODE REVIEW

**Comment by Ch3ck** [comment]
@skycoin I've made the corrections here

**Comment by Ch3ck** [comment]
@skycoin I've fixed all merge conflicts with this PR.

**Comment by Ch3ck** [comment]
@skycoin any updates here?

**Comment by Ch3ck** [comment]
It can always be repopened when you're ready to review @skycoin

**Comment by gz-c** [comment]
Sorry this wasn't merged at the time.  Now it would be more difficult to resolve these conflicts than to redo the corrections, so I'm closing it.  What tools did you run on the source to find these?

**Pull request closed without merging**
