### PR TITLE
Build electron only when merging to master branch

### LINKED ISSUE #684: Don't run electron builds in travis for PR commits
Only run them when merging to `develop` or `master` branch or for tagged branches.

Can use special travis environment variables in a bash script to control this:

https://docs.travis-ci.com/user/environment-variables/

e.g. `TRAVIS_BRANCH`, `TRAVIS_TAG`, `TRAVIS_PULL_REQUEST`

### PR DESCRIPTION
**Pull request by iketheadore**
Fix #684

### CODE REVIEW

**Comment by gz-c** [comment]
Have it build when merging to develop too
Or anything that isn't a PR

**Comment by iketheadore** [comment]
So we need to do build for every commits, except the PRs?

**Comment by gz-c** [comment]
Yes, its ok if the ci build for develop branch is slow, we dont need to wait for it, and in case there is problem with the build we will know about it before we merge to master

**Comment by iketheadore** [comment]
For appveyor, need to go to AppVeyor's webhook settings on GitHub and disable "pull request" event.

**Pull request merged**
