### PR TITLE
Show banner when all connections are down, fixes #370

### LINKED ISSUE #370: Show banner when all connections are down
If user has no network and connections, then it needs to show banner

### PR DESCRIPTION
**Pull request by vyloy**
1.Implemented #370 Show banner when all connections are down
2.Improved UI styles
3.Added electron min height and width

### CODE REVIEW

**Comment by vyloy** [comment]
Removed dist folder now

**Comment by gz-c** [comment]
need update

**Comment by vyloy** [comment]
Updated

**Comment by gz-c** [comment]
Still has conflicts

**Comment by gz-c** [comment]
@iketheadore do we want this for release? needs conflicts resolved

**Comment by iketheadore** [comment]
@gz-c No, we will leave this to next release.

**Pull request closed without merging**
