### PR TITLE
[lib] fixes #1028 - README file for libskycoin

### LINKED ISSUE #1028: make check fails on OS X due to make build-libc
This fails on OS X, the solution is to do `brew install snaipe/soft/criterion`

* The README should be updated to include this instruction for OS X machines wishing to build libskycoin
* libskycoin should not be built by default in `make check`.  Travis should perform the libskycoin test separately

```
mkdir -p build/usr/tmp build/usr/lib build/usr/include
mkdir -p build/libskycoin bin include
rm -Rf build/libskycoin/*
go build -buildmode=c-shared  -o build/libskycoin/libskycoin.so ./lib/cgo/main.go
go build -buildmode=c-archive -o build/libskycoin/libskycoin.a  ./lib/cgo/main.go
mv build/libskycoin/libskycoin.h include/
cp lib/cgo/tests/*.c build/libskycoin/
gcc -o bin/test_libskycoin_shared build/libskycoin/*.c -lskycoin                    -lcriterion -Iinclude -Ibuild/usr/include -L build/libskycoin -Lbuild/usr/lib
build/libskycoin/check_cipher.c:2:10: fatal error: 'criterion/criterion.h' file not found
#include <criterion/criterion.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [test-libc] Error 1
```

### PR DESCRIPTION
**Pull request by olemis**
refs #1028

### CODE REVIEW

**Comment by gz-c** [comment]
Link to this from the main readme?

**Comment by olemis** [comment]
There is a mention to individual README files in `lib/` subfolders . In aa43a37 I just added client libraries entry in README ToC .

**Comment by gz-c** [comment]
From the main README.md:

```
Client libraries
Skycoin implements client libraries which export core functionality for usage from other programming languages. Read the corresponding README file for further details.
```

This "README" mention is not linked to `lib/cgo/README.md`

**Comment by olemis** [comment]
I see what u mean now , ...

**Pull request merged**
