### PR TITLE
Strand cleanup

### PR DESCRIPTION
**Pull request by gz-c**
Makes a common `daemon.strand` package with a strand method.

`func Strand(logger *logging.Logger, c chan Request, name string, f func() error) error`

This method will add logging and record time automatically.

`daemon.Gateway`, `daemon.Visor` and `gnet.Pool` switched to use this strand.

Removes use of `recover()` for closed channel write in `gnet.ConnectionPool`.

Removes use of strand in `pex.Pex`, because this strand used a mutex lock and not a channel.  It is less complicated to call lock/unlock than call strand.  The mutex switched to an RWMutex since many operations only need a read lock.

Includes `DisableNetworking` fixes for `daemon.Visor`, see #533 first.  This has improvement upon changes to strand() from there.

### CODE REVIEW

**Comment by gz-c** [comment]
pushed fix

**Comment by gz-c** [comment]
show me log sample, i didn't see many, should only log when stand is slow or fails

**Comment by iketheadore** [comment]
[skycoin.gnet:DEBUG] Stranding daemon.gnet.ConnectionPool.SendMessage
[skycoin.gnet:DEBUG] strand precall daemon.gnet.ConnectionPool.updateLastSent
[skycoin.gnet:DEBUG] Stranding daemon.gnet.ConnectionPool.updateLastSent
[skycoin.gnet:DEBUG] strand precall daemon.gnet.ConnectionPool.updateLastRecv
[skycoin.gnet:DEBUG] Stranding daemon.gnet.ConnectionPool.updateLastRecv
[skycoin.daemon:DEBUG] Received pong from 47.88.33.156:6000
[skycoin.gnet:DEBUG] strand precall daemon.gnet.ConnectionPool.updateLastRecv
[skycoin.gnet:DEBUG] Stranding daemon.gnet.ConnectionPool.updateLastRecv
[skycoin.daemon:DEBUG] Received pong from 178.62.225.38:6000
[skycoin.gnet:DEBUG] strand precall daemon.gnet.ConnectionPool.updateLastRecv
[skycoin.gnet:DEBUG] Stranding daemon.gnet.ConnectionPool.updateLastRecv
[skycoin.daemon:DEBUG] Received pong from 45.32.235.85:6000
[skycoin.gnet:DEBUG] strand precall daemon.gnet.ConnectionPool.updateLastRecv
[skycoin.gnet:DEBUG] Stranding daemon.gnet.ConnectionPool.updateLastRecv
[skycoin.daemon:DEBUG] Received pong from 35.157.164.126:6000
[skycoin.gnet:DEBUG] strand precall daemon.gnet.ConnectionPool.SendPings
[skycoin.gnet:DEBUG] Stranding daemon.gnet.ConnectionPool.SendPings
[skycoin.gnet:DEBUG] strand precall daemon.gnet.ConnectionPool.SendMessage
[skycoin.gnet:DEBUG] Stranding daemon.gnet.ConnectionPool.SendMessage
[skycoin.gnet:DEBUG] strand precall daemon.gnet.ConnectionPool.ClearStaleConnections
[skycoin.gnet:DEBUG] Stranding daemon.gnet.ConnectionPool.ClearStaleConnections
[skycoin.gnet:DEBUG] strand precall daemon.gnet.ConnectionPool.updateLastSent
[skycoin.gnet:DEBUG] Stranding daemon.gnet.ConnectionPool.updateLastSent
[skycoin.gnet:DEBUG] strand precall daemon.gnet.ConnectionPool.updateLastRecv
[skycoin.gnet:DEBUG] Stranding daemon.gnet.ConnectionPool.updateLastRecv
[skycoin.gnet:DEBUG] strand precall daemon.gnet.ConnectionPool.updateLastRecv
[skycoin.gnet:DEBUG] Stranding daemon.gnet.ConnectionPool.updateLastRecv
[skycoin.daemon:DEBUG] Received pong from 176.9.47.13:6000
[skycoin.daemon:DEBUG] Reply to ping from 176.9.47.13:6000
[skycoin.gnet:DEBUG] strand precall daemon.gnet.ConnectionPool.SendMessage
[skycoin.gnet:DEBUG] Stranding daemon.gnet.ConnectionPool.SendMessage
[skycoin.gnet:DEBUG] strand precall daemon.gnet.ConnectionPool.updateLastSent
[skycoin.gnet:DEBUG] Stranding daemon.gnet.ConnectionPool.updateLastSent
[skycoin.gnet:DEBUG] strand precall daemon.gnet.ConnectionPool.ClearStaleConnections
[skycoin.gnet:DEBUG] Stranding daemon.gnet.ConnectionPool.ClearStaleConnections
[skycoin.gnet:DEBUG] strand precall daemon.gnet.ConnectionPool.SendPings
[skycoin.gnet:DEBUG] Stranding daemon.gnet.ConnectionPool.SendPings
[skycoin.gnet:DEBUG] strand precall daemon.gnet.ConnectionPool.updateLastRecv
[skycoin.gnet:DEBUG] Stranding daemon.gnet.ConnectionPool.updateLastRecv
[skycoin.daemon:DEBUG] strand precall daemon.Visor.RecordBlockchainHeight
[skycoin.daemon:DEBUG] Stranding daemon.Visor.RecordBlockchainHeight
[skycoin.daemon:DEBUG] strand precall daemon.Visor.GetSignedBlocksSince
[skycoin.daemon:DEBUG] Stranding daemon.Visor.GetSignedBlocksSince
[skycoin.daemon:DEBUG] Got 0 blocks since 3534
[skycoin.gnet:DEBUG] strand precall daemon.gnet.ConnectionPool.updateLastRecv
[skycoin.gnet:DEBUG] Stranding daemon.gnet.ConnectionPool.updateLastRecv
[skycoin.gnet:DEBUG] strand precall daemon.gnet.ConnectionPool.updateLastRecv
[skycoin.gnet:DEBUG] Stranding daemon.gnet.ConnectionPool.updateLastRecv
[skycoin.gnet:DEBUG] strand precall daemon.gnet.ConnectionPool.SendMessage
[skycoin.gnet:DEBUG] Stranding daemon.gnet.ConnectionPool.SendMessage
[skycoin.daemon:DEBUG] strand precall daemon.Visor.HeadBkSeq
[skycoin.daemon:DEBUG] Stranding daemon.Visor.HeadBkSeq
[skycoin.gnet:DEBUG] strand precall daemon.gnet.ConnectionPool.updateLastSent
[skycoin.gnet:DEBUG] Stranding daemon.gnet.ConnectionPool.updateLastSent

**Comment by gz-c** [comment]
fixed

**Comment by iketheadore** [comment]
ok 👍

**Pull request merged**
