### PR TITLE
writing home for electron tests since compiling

### PR DESCRIPTION
**Pull request by stdevHan**
writing start for electron tests from the compiled, configuring test.js for tests with spectron + mocha + chai

### CODE REVIEW

**Comment by samuelvisscher** [comment]
Hi Han, thank you for your pull request, but I'm not entirely sure what I'm supposed to do with this. Could you give us some more information?

**Comment by stdevHan** [comment]
Hello visscherio, is to be able to have a forced foot, to be able to write the tests with Spectron, example cases # 1011.

**Comment by samuelvisscher** [comment]
Could you add a real example test (for example asserting that the gui has been loaded) and clean up the code?

**Comment by olemis** [comment]
@samuelvisscher we'll try to look into this in the next few days . Sorry for the delay to reply .

**Pull request closed without merging**
