### PR TITLE
Use the hardware wallet daemon

### PR DESCRIPTION
**Pull request by Senyoret1**
This PR is not ready for review, as there are still many changes being made to the daemon and the code still needs to react correctly in case of some problems (mainly when there are connection schemes and when the daemon is not running).

Changes:
- Now the connection to the hardware wallet is done through the daemon and not the JS library. However, the code for connecting using the JS library is still present and can be activated with a variable (this could be changed when finishing the PR).

Does this change need to mentioned in CHANGELOG.md?
No

### CODE REVIEW

**Comment by Senyoret1** [comment]
This PR should be ready for review now. An important thing to take into account is that I deactivated the integration with the daemon in one of the last commit, so for testing it is necessary to set `AppConfig.useHwWalletDaemon` to true.

**Comment by Senyoret1** [comment]
There are still various pending PRs that add new features to the integration with the hardware wallet using the JS library. After merging those PRs the new features will have to be added to this PRs or a new one (if this one is already merged).

**Comment by gz-c** [comment]
@Senyoret1 which PRs is this waiting on?

**Comment by Senyoret1** [comment]
https://github.com/skycoin/skycoin/pull/2235 first and then https://github.com/skycoin/skycoin/pull/2258 . However, it is not really necessary to merge those PRs before merging this one.

**Comment by Senyoret1** [comment]
Moved to https://github.com/skycoin/skycoin/pull/2367

**Pull request closed without merging**
