### PR TITLE
Small fixes for the GUI

### PR DESCRIPTION
**Pull request by Senyoret1**
Changes:
- Small fix for the code that disables currency selection while creating a transaction.

- Show a spinner while connecting with the hw wallet for changing the device label.

Does this change need to mentioned in CHANGELOG.md?
No

### CODE REVIEW

**Comment by Senyoret1** [comment]
The last commit includes the following changes:

- The timeout for the connection with the hw wallet daemon was ajusted.

- The error message for when the connection with the hw wallet daemon is closed due to the timeout was improved.

- Now the double button in the nav bar is reset every time the user enters in a page that shows it, to make it work in a more consistent way.

**Comment by Senyoret1** [comment]
The timeout was modified again due to the changes made in https://github.com/skycoin/skycoin/pull/2406

**Comment by Senyoret1** [comment]
The latest commit adds additional improvements to how the double button in the nav bar works.

**Comment by gz-c** [comment]
Merge conflict

**Comment by Senyoret1** [comment]
Conflicts solved

**Pull request merged**
