### PR TITLE
[libc] fixes #1191 fixes #1628 - Automatic generation of go functions to export to C

### LINKED ISSUE #1191: Translate and test the whole set of libskycoin API
- [x] Wrappers for `libskycoin` API functions generated with https://github.com/simelo/cgogen (ensure it compiles).
- [x] Translate skycoin test suite from go to c (see simelo/cgogen#1) and ensure all test cases will pass when running it against static and shared versions of `libskycoin` .
- [x] Test against cipher golden file(s) test suite , see #1436 
- [x] Changes in test suite due to changes in `catchApiPanic` (after #1649 )
- [x] `Ripemd160` hash methods in cipher crypto API (somehow missing ...)

### LINKED ISSUE #1628: Checks relying on secp256k1 for cipher golden test suite
This is the part of the code that has to be implemented

```golang
     // TODO : Translate once secp256k1 be part of libskycoin
     /*
     validSec := secp256k1.VerifySeckey(s[:])
     if validSec != 1 {
       return errors.New("secp256k1.VerifySeckey failed")
     }

     validPub := secp256k1.VerifyPubkey(p[:])
     if validPub != 1 {
       return errors.New("secp256k1.VerifyPubkey failed")
     }
     */
```

This is a continuation of #1537 since `secp256k1` API endpoints will get to `develop` after merging (now open) PR #1281 for #1191 .

### PR DESCRIPTION
**Pull request by stdevEclipse**
Fixes #1191 
- New generated code is compilable with make build-libc.
Changes:
- Wrapper for Go functions that can exported to c library. All functions are automatically generated by cgogen. Avoided functions that use function types, interfaces, map or external types, unless specified that these types are replaced by handles or other custome types.
- Code that was hand-written was kept intact. 
- Some minor bugs in generated code was fixed by hand. Due to array sizes using constants or complex expressions.
- Checks relying on secp256k1 for cipher golden test suite

### CODE REVIEW

**Comment by olemis** [comment]
@stdevEclipse [Travis build](https://travis-ci.org/skycoin/skycoin/builds/368264819?utm_source=github_status&utm_medium=notification) was not successful . Could you take a look and bring it back to green ?

**Comment by stdevEclipse** [comment]
Making with build-libc works perfectly for me. However using test-libc reports error related to missing "criterion.h". Is that the issue?
I didn't take care about that because I haven't made anything related to testing.

**Comment by olemis** [comment]
@stdevEclipse please type the number of **total** test cases in commit message so that it will be registered the progress of the whole test suite as you move forward . I know you only test a subset while developing, but before committing run it all ; otherwise it's confusing

**Comment by stdevEclipse** [comment]
There was an error in libc when compiling inside a submodule. The issue was related to exporting function with parameter of a type defined inside vendor.
The functions are:
- SKY_cli_RPCClientFromContext
- SKY_cli_ConfigFromContext

Solution was to call original function code in wrapper, instead of calling the original functions. In both cases original functions were only one line of code.

Example:

func SKY_cli_RPCClientFromContext(_c C.Context__Handle, _arg1 *C.WebRpcClient__Handle) (____error_code uint32) {
	____error_code = 0
	defer func() {
		____error_code = catchApiPanic(____error_code, recover())
	}()
	c, okc := lookupContextHandle(_c)
	if !okc {
		____error_code = SKY_ERROR
		return
	}
	//Do not call c.RPCClientFromContext
	webrpcClient := c.App.Metadata["rpc"].(*webrpc.Client)
	*_arg1 = registerWebRpcClientHandle(webrpcClient)
	return
}

**Comment by gz-c** [comment]
The only module that matters is `cipher`

**Comment by olemis** [comment]
@stdevEclipse @stdevHan , starting from this patch please create a new PR (i.e. branch) and add **only** `cipher` and `coin` .

**Pull request closed without merging**
