### PR TITLE
refs #1554 Fixed issue when removing wallet.

### LINKED ISSUE #1554: Error in skycoin when creating and deleting a wallet with a specific seed and then creating with the same seed.
Creating a wallet with a given specific seed, then deleting and unloading the wallet should allow creating a new wallet with the same seed.
There is a test in libc that is failing because of this. The test passes the first time but fails when executing again. First test is made with static library and second test with shared library. The node is not restarted between the two executions.

### PR DESCRIPTION
**Pull request by stdevEclipse**
Remove reference to wallet first address in field firstAddrIDMap.

Fixes #1554 

Changes:
- When deleting a wallet update map field firstAddrIDMap. This allows creating a wallet with the same seed.

Does this change need to mentioned in CHANGELOG.md?
No

### CODE REVIEW

**Comment by gz-c** [comment]
/wallet/unload is only added to help with integration tests

**Comment by iketheadore** [comment]
Yes, I will add comment about it.

**Comment by olemis** [comment]
@stdevEclipse , travis build is failing .

**Comment by gz-c** [comment]
This will overwrite existing wallet files on disk. There is no problem with `/wallet/unload`

**Pull request closed without merging**
