### PR TITLE
Fixes skcoin: 72 & 77- Change address on send page and removed Icons.

### PR DESCRIPTION
**Pull request by Ch3ck**
Fixes Issue [Skycoin: 72](https://skycoin.atlassian.net/browse/SKYCOIN-76?jql=project%20%3D%20SKYCOIN%20AND%20resolution%20%3D%20Unresolved%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC). Changes address on send page to Pay-to.

### CODE REVIEW

**Comment by Ch3ck** [comment]
`gulp install` fails to generate `./dev` folder. Had to manually copy the wallet html. I don't know if there's anything wrong I did.

**Comment by Ch3ck** [comment]
Issue fixed. Had an outdated npm and nodejs installation.

**Comment by Ch3ck** [comment]
Fixes : [Wallet] Remove cloud icons.

**Comment by skycoin** [comment]
Great! Merge! Thanks

**Pull request merged**
