### PR TITLE
Process links requesting coins

### PR DESCRIPTION
**Pull request by Senyoret1**
Changes:
- Now the forms for sending coins have an option for reading links created following the Skycoin URI specification ( https://github.com/SkycoinProject/skycoin#uri-specification ), which are created by the QR code modal window and the mobile wallet. The link is processed and the form is populated with the data obtained from it. Before this, there was no way for using the links with the desktop wallet.
- Modifications were made to the simple form, to make it able to send an especific number of hours, but only when using a link.

Note:
The electron build is still not integrated with the deep linking features of the OSs.

Note:
Migrated from https://github.com/SkycoinProject/skycoin/pull/305

Does this change need to mentioned in CHANGELOG.md?
No

### CODE REVIEW

**Comment by iketheadore** [comment]
Would you mind to upgrade the electron to 10.1.6, Snyk detected a high severity vulnerability of 10.1.5. Thank you.

**Comment by Senyoret1** [comment]
Thank you for checking. I updated the branch for passing the tests and updated Electron in https://github.com/skycoin/skycoin/pull/2545

**Comment by iketheadore** [comment]
@Senyoret1 conflicts.

**Comment by Senyoret1** [comment]
Conflicts solved

**Review by iketheadore — APPROVED** [review]

**Pull request merged**
