### PR TITLE
Use the devSkycoinTransactionSign function of the hardware wallet

### LINKED ISSUE #2161: Encode binary in hexdump to communicate with hardware wallet
Some changes might be needed in electron wallet after merging skycoin/hardware-wallet#66 to fix skycoin/hardware-wallet#65 . Encoding changed from `base58` to `hex`.

### PR DESCRIPTION
**Pull request by Senyoret1**
Fixes #2161

Changes:
- Now, when using a hardware wallet, the transactions are signed with the `devSkycoinTransactionSign` function, instead of `devSkycoinSignMessage`. This means that the user can now see and confirm the details of the transaction on the hardware wallet before it is signed.

Notes:
- To be able to test this PR it is necessary to use a hardware wallet with the lastest changes made on the develop branch of https://github.com/skycoin/hardware-wallet
- To create this PR it was necessary to update the version of the hardware-wallet-js library used by the desktop wallet. Doing this added a new error: if the user selects the option for wiping the hardware wallet and cancels the operation on the device, Electron displays an error message and the desktop wallet stop working until it is restarted. The error was solved in https://github.com/skycoin/hardware-wallet-js/pull/48 and the change must be added to the desktop wallet once that PR is merged.

Does this change need to mentioned in CHANGELOG.md?
No

### CODE REVIEW

**Comment by Senyoret1** [comment]
https://github.com/skycoin/hardware-wallet-js/pull/48 was merged and the hardware-wallet-js lib version used by this PR was updated, so the problem while wiping the wallet is solved.

**Comment by Senyoret1** [comment]
I did some testing and saw that at this moment the function of the hardware wallet that allows to create transactions can only receive up to 8 inputs and 8 outputs, so in the last commit I modified the function of the desktop wallet to throw an error if those limits are not respected.

I'm going to change this again after https://github.com/skycoin/hardware-wallet/issues/79 is solved.

**Comment by Senyoret1** [comment]
Recently a change was made in the hardware wallet repository and now, when using the lasted version of the firmware, the signatures are returned in hex instead of Base58. The last commit updates the skycoin-lite lib to make this PR work with the latest firmware version.

This fixes #2161

**Comment by olemis** [comment]
@Senyoret1 does this need further changes after merging skycoin/hardware-wallet#93 ? I'm mainly thinking of changing coins from `uint32_t` => `uint64_t` in firmware , not the coins display part .

**Comment by olemis** [comment]
Approved after reading [this comment](https://github.com/skycoin/hardware-wallet-js/pull/56#pullrequestreview-204519901)

**Comment by Senyoret1** [comment]
Yes and no. The PR will work correctly without any change, but it will continue having problems with large coin values until the version of hardware-wallet-js that I added as dependency is updated. However, it would be best to do the update in another PR when integrating new features, so there should be no problems to merge this.

**Pull request merged**
