### PR TITLE
Show different errors when decrypting seed

### LINKED ISSUE #1276: Password always incorrect for backup seed / GET /wallet/seed
This could be a backend problem or a frontend problem

@iketheadore 
@mahansky

### PR DESCRIPTION
**Pull request by mahansky**
Fixes #1276

Changes:
- show different errors based on response status code
screen shot 2018-04-19 at 12 34 59
screen shot 2018-04-19 at 12 33 25

### CODE REVIEW

**Comment by Senyoret1** [comment]
Tested. Everything works fine.

**Comment by mahansky** [comment]
Added better error handling https://github.com/skycoin/skycoin/issues/1295#issuecomment-382945732

**Comment by mahansky** [comment]
#1301 adds the "required" validator.

I added a util function to parse the response message according to your suggestions

**Comment by Senyoret1** [comment]
Tested. Good improvement.

**Pull request merged**
