### PR TITLE
skycoin crashed when getblocksbyseq

### PR DESCRIPTION
**Pull request by zhiyuan2007**
skycoin crashed when run command getblocksbyseq and seq > blockcount,  because return value is incorrect, error should not nil

skycoin-crashed

### CODE REVIEW

**Comment by iketheadore** [comment]
Do not return that error, the `GetBlocksInDepth` need to check the nil, and `GetBlockBySeq` is designed to return nil on not found.

**Comment by zhiyuan2007** [comment]
crashed have to handled by other manner

**Comment by gz-c** [comment]
The caller of `GetBlockBySeq` needs to check for `nil` blocks

**Comment by gz-c** [comment]
#617 #616

**Pull request closed without merging**
