### PR TITLE
Desktop wallet fixes

### PR DESCRIPTION
**Pull request by iketheadore**
Fixes: #2083

Does this change need to mentioned in CHANGELOG.md?
yes

### CODE REVIEW

**Comment by Senyoret1** [comment]
The white screen problem is a bit complicate for me because I can not reproduce it on my pc, so I’m guessing some things.

Placing `event.returnValue = '';` in the line 82 solves the white screen problem, but should generate a new one. The `getSavedWalletsDataSyncEvent = event;` part above should make that line unnecessary, since thanks to it a valid value would be assigned to `event.returnValue` as soon as `setWalletsFolderPath` is called. This, of course, means assuming that `setWalletsFolderPath` will be called at some point, and the error may be there.

Here is the situation: if `setWalletsFolderPath` is never called, the screen will remain white and adding `event.returnValue = '';` in the line 82 solves the problem because assigning a value to `event.returnValue` allows the browser code to continue working instead of stay waiting for a response. However, as `setWalletsFolderPath` was never called, the code does not know were to save the hardware wallets info, so when connecting a hardware wallet `hwSaveWalletsDataSync` will be called and it will throw this error, making the hardware wallet integration unusable:

err

Taking all this into account, a more adequate solution may be to assure that `setWalletsFolderPath` is called with a valid value. My guess is that this part on lines 339-345 is failing:
https://github.com/skycoin/skycoin/blob/c458da61bc9912f85dd447947e01784e69c4deba/electron/src/electron-main.js#L339-L345

As you can see, the `.catch` part is empty. You can change the catch part to something like `.catch(e => { console.log(e); });` to see if it is failing and why. If `.catch` is being called, maybe the problem can be solved by adding `const url = require('url');` at the top of the file and replacing `.get(e.url + '/api/v1/wallets/folderName')` with `.get(new url.URL('/api/v1/wallets/folderName', e.url).href) `. Other solutions could be to create a retry mechanism, like the one you created to wait until the splash screen is loaded, or use a default path in case of error/timeout.

Apart from that, I do not understand what the purpose of `splashLoaded` is. The splash screen is almost guaranteed to be loaded before `if (line.indexOf(marker) !== -1)` is true and, even if it is not, it should not generate any problem. The operation of the splash screen, as far as I know, has not changed since version 0.24.0.

**Comment by iketheadore** [comment]
@Senyoret1 I will add log in the catch to have a test. 

If I don't add the `splashLoaded` to make sure the splash page is loaded before loading the wallet, it will have `did-fail-load` error, and show the error page.

**Comment by Senyoret1** [comment]
@gz-c Just the wallet name, the addresses and if the user completed the configuration the last time it was connected. The data is used to allow to see the addresses and balance even when the device is not connected.

**Comment by iketheadore** [comment]
@Senyoret1, I find it's the problem of my windows laptop, @gz-c do you remember I said that the wallet always try to connect to an unreachable proxy of port 1087, that's the problem, the `axios.get` will fail to get wallet folderName cause it try to connect the `0.0.0.0:1087`.  I don't know why the proxy still exist, I've disabled it,  and tested to run a new proxy with a new port, the log still says it try to connect the proxy of port 1087. Anyway I think the white page should not be a problem on normal windows.

**Comment by gz-c** [comment]
@senyoret1 should we add an api to the back end to store arbitrary data?

**Comment by gz-c** [comment]
I would prefer to remove the need for nodejs's fs interface. Also, where is the data saved?

@mahansky recently mentioned a possible need for a generic way to save data in a file in the data folder through the API, but I forget for which feature

**Comment by mahansky** [comment]
It was for the swaplab integration

**Pull request merged**
